Capture phone number
Fitsnitch-CS480/fitsnitch-app pull request #20
Opened 2022-02-08 01:37 UTC by Filaipus

Ignoring the name of the branch, this changes all the data captured (to include phone number, first name and last name) and fixes some bugs with the sign-up process. (Also right now some fields are optional and we are not screaming at it, I'll leave those details for later)

It also totally changes the way the SignUpView is formatted, which will transfer to LoginView later (I know it's non important but the hard-codded layout was bugging me). Experience should be pretty smooth. 

WE DO NOT CONFIRM PHONE NUMBER with this PR. It will cost money and we need to figure out with Andre who's paying for that (it's cents but it would be nice to figure that out now). https://aws.amazon.com/sns/sms-pricing/

2022-02-08 17:10 UTC, connercharles requested changes
Posted a question and added a comment

2022-02-08 17:10 UTC, connercharles commented on react-native-app/views/SignUpView.tsx
> +      //may need to take this out of the signUpFunction since it's not doing the change immediatly as the Auth.signUp gets called
So we need these checks just because the cognito checks are slower? is that what you were saying?

2022-02-08 17:10 UTC, connercharles commented on react-native-app/views/SignUpView.tsx
> +    // justifyContent: 'center',
If the layout is all done and we don't need these commented stuff, could you get rid of them please? 😄

2022-02-08 18:15 UTC, amj311 commented on react-native-app/views/SignUpView.tsx
> +      //may need to take this out of the signUpFunction since it's not doing the change immediatly as the Auth.signUp gets called
If you want  to add the "+1" to the phone number, you could just save the updated number to a local variable (inside signupFunction()) and send that local variable as phone_number instead of the state phoneNumber

2022-02-14 23:45 UTC, Filaipus commented on react-native-app/views/SignUpView.tsx
> +      //may need to take this out of the signUpFunction since it's not doing the change immediatly as the Auth.signUp gets called
Good catch haha

2022-02-14 23:49 UTC, merged