Snitch profile
Fitsnitch-CS480/fitsnitch-app pull request #27
Opened 2022-02-15 18:43 UTC by rcaina

Snitches viewed on user profile, as well as user being able to view snitches of partners and trainees (if user is a trainer)

2022-02-16 03:16 UTC, amj311 requested changes
This looks great! I only have two small comments. One is in the SnitchesView where it looks like the page size was changed to 1.

The other is that we seem to have two PartnerAssociationRequestButton components, but with different capitalization. Do you think that could be resolved in this PR?

2022-02-16 03:16 UTC, amj311 commented on react-native-app/views/SnitchesView.tsx
> +const PAGE_SIZE = 1
It looks like this number might have been changed for testing purposes? I'm not sure we need the snitch feed page size to be just 1. If it was just a test, let's change it back.

2022-02-16 05:35 UTC, rcaina commented on react-native-app/views/SnitchesView.tsx
> +const PAGE_SIZE = 1
Not quite sure why there are 2 PartnerAssociationRequestButton components. When I do a pull on main only one shows up and it says it is up to date. and so same when I merge to this branch. There is only one of those components. Tried to re-commit and all but it says there  is nothing to commit so not sure how to go about getting rid of the extra component. The one that should be kept is the one that is Capitalized at the beginning (PartnerAssociationRequestButton). The other should be deleted

2022-02-16 17:43 UTC, Filaipus commented on react-native-app/views/SnitchesView.tsx
> +const PAGE_SIZE = 1
I think that might be my fault (and github?) 
When I pulled main there was that button but with lowercase P, which made Metro go crazy (no idea how the person that did that change was compiling the project). So I changed it to uppercase P. I guess when I merged github didn't recognize it as a name change and instead as two different files and somehow kept both? Not sure, specially not sure about why NOW it doesn't recognize that there are two files haha

2022-02-17 05:16 UTC, amj311 approved these changes

2022-02-17 05:17 UTC, amj311 commented on react-native-app/views/SnitchesView.tsx
> +const PAGE_SIZE = 1
It's been happening elsewhere, so it's probably not your fault

2022-02-17 05:18 UTC, amj311 commented on react-native-app/views/SnitchesView.tsx
> +const PAGE_SIZE = 1
> Not quite sure why there are 2 PartnerAssociationRequestButton components. When I do a pull on main only one shows up and it says it is up to date. and so same when I merge to this branch. There is only one of those components. Tried to re-commit and all but it says there is nothing to commit so not sure how to go about getting rid of the extra component. The one that should be kept is the one that is Capitalized at the beginning (PartnerAssociationRequestButton). The other should be deleted

Okay, we can leave it for now and address it later

2022-02-17 05:52 UTC, merged