Feat/firebase auth
Fitsnitch-CS480/fitsnitch-app pull request #60
Opened 2023-03-18 19:43 UTC by rcaina

Add Authentication for app using Firebase Authentication! (No need for Amplify or Cognito. Authentication is through email, SMS will be added later on)

- New packages: 
 -- firebase/auth: Allows Authentication through Firebase
 
- Main Updated Files: Login, SignUp, Confirmation, AuthService, AuthWrapper
- Removed: Amplify, Encrypted-storage (Firebase takes care of persistent login), unused feature "Demo snitch" from settings.

2023-03-19 02:03 UTC, amj311 requested changes
This looks great! So much simpler. Just a few tiny comments about some error catching

2023-03-19 02:03 UTC, amj311 commented on react-native-app/services/AuthService.ts
> +				if (error.code === 'auth/email-already-in-use') {
Is 'auth/email-already-in-use' an error we would expect to get back from a login attempt?

2023-03-19 02:03 UTC, amj311 commented on react-native-app/services/AuthService.ts
> +				if (error.code === 'auth/email-already-in-use') {
Are there error options here for an invalid password?

2023-03-19 02:03 UTC, amj311 commented on react-native-app/services/AuthService.ts
> +			console.log({error})
We should probably display a message to the user if there is an error with the verification email. We wouldn't want to make them wait on nothing

2023-03-19 02:03 UTC, amj311 commented on react-native-app/services/AuthService.ts
> +			console.log({error})
We should probably display a message to the user if there is an error with the verification email. We wouldn't want to make them wait on nothing

2023-03-20 15:35 UTC, rcaina commented on react-native-app/services/AuthService.ts
> +				if (error.code === 'auth/email-already-in-use') {
These were built in errors that came as part of the code snippet directly from firebase. I could look into invalid password error options.

2023-03-20 15:36 UTC, rcaina commented on react-native-app/services/AuthService.ts
> +			console.log({error})
I think i completely forgot about the error handling when putting this together haha. I was so focused on getting it all to pass.

2023-03-20 15:36 UTC, rcaina commented on react-native-app/services/AuthService.ts
> +			console.log({error})
will do

2023-03-21 10:44 UTC, amj311 approved these changes

2023-03-22 03:01 UTC, merged